config/routes.rb
Rails.application.routes.draw do
  root to: 'shops#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  get 'category/:id',to: 'shops#category', as: 'category'
  get 'search', to: 'shops#search'
  post 'addstock', to: 'items#addstock'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  resources :items
  resources :shops
  resources :user_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  belongs_to :category
  
  validates :name, presence: true, length: { maximum: 30 }
  validates :price,  numericality: { only_integer: true }, length: { maximum: 10 }
  validates :content, presence: true, length: { maximum: 100 }
  validates :stock , numericality: { only_integer: true }, length: { maximum: 3 }
  
  scope :search, -> (search_params) do
    return if search_params.blank?
    name_like(search_params[:name]).category_id(search_params[:category_id])
  end

  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :category_id, -> (category_id) { where(category_id: category_id) if category_id.present? }
  
  has_many :user_items,dependent: :destroy
  has_many :buyers, through: :user_items, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name,  presence: true, length: { maximum:50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    validates :bank,  presence: true, length: { maximum:20 }
    validates :account_number,  numericality: { only_integer: true }, length: { maximum: 10 }
    
    has_secure_password
    
    has_many :items
    has_many :user_items
    has_many :buys, through: :user_items, source: :item
    
    
    def shop(shop_item)
     self.user_items.build(item_id: shop_item.id)

    end
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :quantity , numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy,:edit]
  
  def index
    @items = current_user.items.order(id: :desc).page(params[:page]).per(10)
  end

  def show
    @item=Item.find(params[:id])
  end

  def new
    @item = current_user.items.build
  end

  def create
    @item =current_user.items.build(items_params)
    if @item.save
      flash[:success] = '商品を登録しました。'
      redirect_to items_path
    else
      flash.now[:danger] = '商品の登録に失敗しました。'
        render :new
    end
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(items_params)
      flash[:success] = '商品情報は正常に更新されました'
      redirect_to @item
    else
      flash.now[:danger] = '商品情報は更新されませんでした。'
      render :edit
    end
  end
  
  def addstock
    @item=Item.find(params[:id])
    @item.increment(:stock, params[:item][:add_stock].to_i)
    if params[:item][:add_stock].present? && @item.save
      flash[:success] = '在庫数が更新されました。'
      redirect_to @item
    else
      @items = current_user.items.order(id: :desc).page(params[:page]).per(10)
      flash.now[:danger] = '在庫数は更新されませんでした。'
      render :index
    end
  end

  def destroy
    @item.destroy
    flash[:success] = '登録商品を削除しました。'
    redirect_to items_path
  end
  
  private
  
  def items_params
    params.require(:item).permit(:name,:price,:category_id,:content,:image,:stock)
  end  
  

  def correct_user
    @item = current_user.items.find_by(id: params[:id])
    unless @item
    redirect_to items_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    session[:name] = nil
    session[:category] = nil
    session[:category_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :require_user_logged_in
  def index
    session[:category] = nil
    session[:category_id] = nil
    session[:name] = nil
    @items = Item.order(id: :desc).page(params[:page]).per(10)
  end
  
  def search
    session[:name] = params[:search][:name]
    @search_params = user_search_params
    @items =Item.search(@search_params).order(id: :desc).page(params[:page]).per(10)
    render "shops/index"
  end
  
  def category
    session[:name] = nil
    if params[:id] != '999'
      category = Category.find(params[:id])
      session[:category] = category.category
      session[:category_id] = params[:id]
      @items =Item.where(category_id: params[:id]).order(id: :desc).page(params[:page]).per(10)
    else
      session[:category] = nil
      @items = Item.page(params[:page]).per(10)
    end
    render "shops/index"
  end

  def create
    item = Item.find(params[:id])
    current_user.buy(item)
    flush[:success] = '商品の購入を確定しました。振り込み確後、商品を発送します。'
    render "shops/result"
  end
  
  
  def user_search_params
    params.fetch(:search, {}).permit(:name,:category_id )
  end
end

app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController
  before_action :require_user_logged_in
    def create
      @item = Item.find(params[:item_id])
      @user_item = current_user.shop(@item)
      @user_item.quantity = params[:user_item][:quantity]
        if @user_item.quantity.nil? || @item.stock >= @user_item.quantity
          if @user_item.save
            @item.decrement(:stock, @user_item.quantity)
            @item.save
            flash[:success] = '商品の購入を確定しました。振り込み確認後、商品を発送します。'
            ContactMailer.send_when_admin_reply(@user_item).deliver
            NotificationMailer.send_when_user_reply(@user_item).deliver
            redirect_to @user_item
          else
            flash.now[:danger] = '商品の購入に失敗しました。'
            @items =Item.name_like(session[:name]).category_id(session[:category_id]).order(id: :desc).page(params[:page]).per(10)
            render 'shops/index'
          end
        else
          flash.now[:danger] = '在庫数が不足しています。'
          @items =Item.name_like(session[:name]).category_id(session[:category_id]).order(id: :desc).page(params[:page]).per(10)
          render 'shops/index'
        end
    end
    
    def show
        @user_item = UserItem.find(params[:id])
        @item = @user_item.item
        @user = @item.user
    end
    
    def index
        @user_items1 = current_user.user_items
        @user_items2 = current_user.user_items.order(id: :desc).page(params[:page]).per(10)
    end
    
    private 
    def user_item_params
      params.require(:user_item).permit(:user_id,:item_id) 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'アカウントを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'アカウントの登録に失敗しました。'
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :bank, :account_number,:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
    def category_all
      @categories = Category.all
      return @categories
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/items/edit.html.erb
<%= form_with(model: @item, local: true,method: :put) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>

<h1 class="mb-5"><%= @item.name %>の商品編集ページ</h1>

<div class="row">
  <aside class="col-sm-12 col-md-4">
   <div class="form-group">
     <img class="mr-2 rounded">
    <%if @item.image.present? %>
      <%= image_tag @item.image.url , id: :img_prev, :width =>'200' %>
    <%else%>
      <%= image_tag ('/uploads/tmp/NO_IMAGE.png'), id: :img_prev, :width =>'200' %>
    <%end%> 
    </img>
    <%= f.file_field :image,class:'mt-3' ,id: :botton_img%>
    </div>
  </aside>

  <div class="col-sm-12 col-md-8">
    <div class="form-group">
      <%= f.label :name, '商品名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price, '価格(円)' %>
      <div class="col-sm-4 col-md-4 row">
        <%= f.text_field :price, class: 'form-control' %>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :category, 'カテゴリー' %>
      <div class="col-sm-4 col-md-4 row">
        <%= f.collection_select :category_id, Category.all,:id,:category,{include_blank: true},{class: 'form-control'}  %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :content, '説明' %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>
  
    <%= f.submit '商品編集', class: 'btn btn-primary' %>
    <%= link_to '一覧へ戻る', items_path, class: 'btn btn-light' %>
  </div>
</div>
<% end %>

<script type="text/javascript">
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#botton_img").change(function(){
        readURL(this);
    });
  });
</script>

app/views/items/index.html.erb
<h1 class="midashi mb-5">商品登録画面</h1>

<%= link_to '商品を新規登録', new_item_path, class: "btn btn-primary" %>

<div class="mt-3">
<ul class="list-unstyled">
  <% @items.each do |item| %>
    <li class="media mb-3  border-bottom border-primary">
      <%if item.image.present? %>
        <img class="mr-2 rounded" src="<%= item.image %>" width="100" alt="">
      <%else%>
        <img class="mr-2 rounded"> <%= image_tag ('/uploads/tmp/NO_IMAGE.png'), :width =>'100' %></img>
      <%end%>
      <div class="media-body row ml-3">
        <div class="col-md-6 ml-6">
          <p>商品名：<%= item.name %></p>
          <p>在庫数：<%= item.stock %></p>
              <%= form_with(model:item,url:addstock_path, local: true,method: :post)do |f| %>
              <%= hidden_field_tag :id, item.id %>
              <div class="input-group mb-3">
                <%= f.number_field :add_stock, min:-100,max:100,step:1 ,class: 'pl-1'%>
                <div class="input-group-append">
                  <%= f.submit '在庫追加', data: { confirm: "在庫数を追加（又は削減）しますか?"}, class: 'btn-primary btn-block btn-sm mt-4.5' %>
                </div>
              </div>
          </div>
       </div>
      <div>
        <%end%>
        <%= link_to '商品詳細', item,class: 'btn btn-light' %>
      </div>
    </li>
  <% end %>
  <%= paginate @items %>
</ul>
</div>

app/views/items/new.html.erb
<%= form_with(model: @item, local: true) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>

<h1 class="mb-5">商品の新規登録ページ</h1>

<div class="row">
  <aside class="col-sm-12 col-md-4">
   <div class="form-group">
     <img class="mr-2 rounded">
    <%if @item.image.present? %>
      <%= image_tag @item.image , id: :img_prev, :width =>'200' %>
    <%else%>
      <%= image_tag ('/uploads/tmp/NO_IMAGE.png'), id: :img_prev, :width =>'200' %>
    <%end%> 
    </img>
    <%= f.file_field :image,class:'mt-3' ,id: :botton_img%>
    </div>
  </aside>

  <div class="col-sm-12 col-md-8">
    <div class="form-group">
      <%= f.label :name, '商品名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price, '価格(円)' %>
      <div class="col-sm-4 col-md-4 row">
        <%= f.text_field :price, class: 'form-control' %>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :category, 'カテゴリー' %>
      <div class="col-sm-4 col-md-4 row">
        <%= f.collection_select :category_id, Category.all,:id,:category,{include_blank: true},{class: 'form-control'}  %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :stock, '在庫数' %>
      <div class="col-sm-3 col-md-3 row">
        <%= f.number_field :stock, min:1,max:10000,step:1 ,class: 'form-control'%>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :content, '説明' %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>
  
    <%= f.submit '商品登録', class: 'btn btn-primary' %>
    <%= link_to '一覧へ戻る', items_path, class: 'btn btn-light' %>
  </div>
</div>
<% end %>

<script type="text/javascript">
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#botton_img").change(function(){
        readURL(this);
    });
  });
</script>

app/views/items/show.html.erb
<h1 class="mb-5"><%= @item.name %>の商品詳細ページ</h1>
<div class="row">
    <div class="col-sm-12 col-md-4">
        <div class="form-group">
        <%if @item.image.present? %>
            <img class="mr-2 rounded" src="<%= @item.image %>" width="200" alt="">
        <%else%>
          <img class="mr-2 rounded"> <%= image_tag ('/uploads/tmp/NO_IMAGE.png'), :width =>'200' %></img>
        <%end%>
        </div>
    </div>

    <div class="col-sm-12 col-md-8">
    <table class="table table-bordered main">
        <tr>
            <th>id</th>
            <td><%= @item.id %></td>
        </tr>
        <tr>
            <th>商品名</th>
            <td><%= @item.name %></td>
        </tr>
        <tr>
            <th>価格</th>
            <td><%= @item.price %>円</td>
        </tr>
        <tr>
            <th>カテゴリ</th>
            <td><%= @item.category.category %></td>
        </tr>
        <tr>
            <th>在庫数</th>
            <td><%= @item.stock %></td>
        </tr>
        <tr>
            <th>説明</th>
            <td><%= @item.content %></td>
        </tr>
    </table>
    <%=link_to 'この商品を編集する',edit_item_path(@item),class: 'btn btn-primary'%>
    <%= link_to 'この商品を削除する', @item, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
    <%= link_to '一覧へ戻る', items_path, class: 'btn btn-light' %>
    </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand navbar-fff3b8 title " href="/">EC-Shopping</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <!--<a href="#" class="navbar-brand navlogin">ログインユーザ</a>-->
          <h5 class="navbar-brand navlogin">ログインユーザ</h5>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to '商品登録', items_path %></li>
              <li class="dropdown-item"><%= link_to '商品購入', shops_path %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'アカウント登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>EcShopping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body class="pen top">
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shops/create.html.erb
<h1>Shops#create</h1>
<p>Find me in app/views/shops/create.html.erb</p>

app/views/shops/index.html.erb
  <%if flash[:danger] != nil%>
  <%= form_with(model: @user_item, local: true)do |f| %>
    <%= render 'layouts/error_messages', model: f.object%>
  <% end %>
  <%end%>
<h1 class="midashi mb-5 san-font">商品購入画面</h1>
<%=link_to '購入履歴へ',user_items_path, method: :get,class: 'btn btn-light '%>
<div class="row">
  <div class="col-md-3 mt-5">
    <table class="table table-bordered category_main category_font table-hover">
      <tr>
        <td><%= link_to '全てのカテゴリ' ,category_path(id: 999) %></td>
      </tr>
      <% category_all.each do |f| %>
      <tr>
        <td><%= link_to f.category ,category_path(id: f.id) %></td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="col-md-9">

        <%= form_with(scope: :search, url: search_path, method: :get, local: true) do |f| %>
        <div class="mb-2 form-group form-inline">
          <label class="mr-2 marukakomi form-control" style="width:97px;">商品名検索</label>
          <div class="input-group inline-block">
            <%= f.text_field :name,:value =>session[:name],:size =>"60",class:'form-control',placeholder:'検索ワード' %>
            <%= f.hidden_field :category_id ,:value =>session[:category_id]%>
            <div class="input-group-append">
              <%= f.submit '検索',class: 'btn-light btn-block text-center btn-sm' %>
            </div>
          </div>
        <% end %>
    </div>
      <h4 class="mt-3"><span class="badge badge-info p-2">カテゴリ：
      <% if session[:category] %>
        <%= session[:category] %></span></h4>
      <% else%>
        全てのカテゴリ</span></h4>
      <%end%>
    
    <div class="mt-3">
      <ul class="list-unstyled">
        <% @items.each do |item| %>
          <li class="media mb-3 border-bottom border-primary">
            <%if item.image.present? %>
              <img class="mr-2 rounded" src="<%= item.image %>" width="100" alt="">
            <%else%>
              <img class="mr-2 rounded"> <%= image_tag ('/uploads/tmp/NO_IMAGE.png'), :width =>'100' %></img>
            <%end%>
            <div class="media-body">
              <label class="ml-4">商品名：<%= item.name %></label><br>
              <label class="ml-4">価格：<%= item.price %>円</label><br>
              <label class="ml-4">説明：<%= item.content %></label>
            </div>
            <div clas="form-group form-inline">
            <label class="mr-3 border_black">在庫数：<%= item.stock %></label>
              <div class="input-group-append">
            <label>購入数：</label>
            <%= form_with(model: @user_items=current_user.user_items.build, local: true)do |f| %>
              <%= hidden_field_tag :item_id, item.id %>
              <%= f.number_field :quantity, min:1,max:10000,step:1, class: 'pl-1' %>
              <%= f.submit '購入', data: { confirm: "購入を確定させますか?" }, class: 'btn-primary btn-block btn-sm mt-4' %>
            <% end %>
              </div>
            </div>
          </li>
        <% end %>
        <%= paginate @items %>
      </ul>
    </div>
  </div>
</div>

app/views/user_items/index.html.erb
<h1 class="midashi mb-5">購入履歴画面</h1>
<% sum = 0 %>
<%@user_items1.each do |user_item1| %>
  <% user_item1.quantity %>
  <% user_item1.item.price %>
  <% sum_price = (user_item1.quantity.to_i)*(user_item1.item.price.to_i) %>
  <% sum += sum_price %>
<% end %>
<h2>購入合計：<%= sum %>円</h2>
<h3 class="rireki mt-4" style="width:180px;">購入履歴</h3>
<div class="mt-3">
  <ul class="list-unstyled">
    <% @user_items2.each do |user_item| %>
      <li class="media mb-3  border-bottom border-primary">
        <%if user_item.item.image.present? %>
          <img class="mr-2 rounded" src="<%= user_item.item.image %>" width="100" alt="">
        <%else%>
          <img class="mr-2 rounded"> <%= image_tag ('/uploads/tmp/NO_IMAGE.png'), :width =>'100' %></img>
        <%end%>
        <div class="media-body ">
          <% sum_price = (user_item.quantity.to_i)*(user_item.item.price.to_i) %>
          <p class="ml-4">商品名：<%= user_item.item.name %></p>
          <p class="ml-4">数量：<%= user_item.quantity %></p>
          <label class="ml-4">価格：<%= user_item.item.price %>円</label><label class="ml-5 border_black">合計額：<%= sum_price %>円</label>
        </div>
      </li>
    <% end %>
    <%= paginate @user_items2 %>
  </ul>
</div>

app/views/user_items/show.html.erb
<h1 class="mb-5">商品購入結果</h1>
<div class="row">
  <div class="col-sm-12 col-md-4">
    <div class="form-group">
        <%if @item.image.present? %>
            <img class="mr-2 rounded" src="<%= @item.image %>" width="200" alt="">
        <%else%>
            <img class="mr-2 rounded"> <%= image_tag ('/uploads/tmp/NO_IMAGE.png'), :width =>'200' %></img>
        <%end%>
    </div>
  </div>

<div class="col-sm-12 col-md-8">
<table class="table table-bordered main">
    <tr>
        <th>商品名</th>
        <td><%= @user_item.item.name %></td>
    </tr>
    <tr>
        <th>価格</th>
        <td><%= @user_item.item.price %>円</td>
    </tr>
    <tr>
        <th>数量</th>
        <td><%= @user_item.quantity %></td>
    </tr>
    <tr>
        <th>合計金額</th>
        <% all = @user_item.quantity.to_i * @user_item.item.price.to_i %>
        <td><%= all %>円</td>
    </tr>
    <tr>
        <th>振込先</th>
        <td>商品登録者：<%= @item.user.name %><br>銀行名　　：<%= @item.user.bank %><br>口座番号　：<%= @item.user.account_number %></td>
    </tr>
</table>

<%=link_to '購入履歴へ',user_items_path, method: :get,class: 'btn btn-light'%>

</div>
</div>

app/views/users/new.html.erb
<%= render 'layouts/error_messages', model: @user %>
<div class="text-center col-md-9 col-lg-6 offset-lg-3 offset-md-2  mb-3">
  <h2 class="top_user">アカウント登録</h1>
</div>

<div class="row ">
  <div class="col-md-9 col-lg-6 offset-lg-3 offset-md-2">
  
    <%= form_with(model: @user, local: true) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group row">
        <div class="form-group col-6">
        <%= f.label :bank, '銀行名' %>
        <%= f.text_field :bank, class: 'form-control' %>
        </div>
        <div class=" form-group col-6">
        <%= f.label :account_number, '口座番号' %>
        <%= f.text_field :account_number, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（再確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>